### ISSUE TITLE
wish: configurable wait time

### ISSUE THREAD

**Issue by markstos** [void666/request-promise-retry#3]
If the error is `429: Over Quota`, you may want to wait 15 minutes before trying again. 

Supporting the "Exponential Backoff" algorithm is also useful if you are contacting a server which is trying to recover from high load,  while at the same time it's being hammered by services which retrying their requests as fast they can waiting for it to come back up.

**Comment by void666** [comment]
@markstos makes sense to add exponential backoff. Adding it as an enhancement.

**Comment by batmat** [comment]
@void666 did you close this on purpose? I believe you wanted to just add the label, but not close this request did you?

**Comment by void666** [comment]
My bad. Reopened it.

**Comment by batmat** [comment]
Feature proposed in PR https://github.com/void666/request-promise-retry/pull/6

**Comment by mmcguff** [comment]
Having number of retries and a wait interval for those retires that you can set by environmental variable would be very helpful.  I am forking this repo and doing just that.  I will PR my branch and you can decide if its worth including.

**Comment by batmat** [comment]
@mmcguff this feature is already ready and used in real conditions in https://github.com/void666/request-promise-retry/pull/6

Interested to hear feedback from there. Let's build more together instead of another implementation from scratch I guess :). Thanks

**Comment by void666** [comment]
Resolved in #6
