### ISSUE TITLE
wish: document which conditions trigger retries.

### ISSUE THREAD

**Issue by markstos** [void666/request-promise-retry#4]
Another retrying module retries when the error is `ECONNRESET` or `ETIMEDOUT`. It appears you retry any time that the `request-promise` would reject. That's a useful detail to clarify in the docs.

**Comment by void666** [comment]
@markstos This is actually the intention of doing the retry. Post adding the [delay mechanism](https://github.com/void666/request-promise-retry/issues/4), no matter what the outcome of the request is, the request will be retried, till not resolved, over the exponential delay and till the number of retries is fulfilled.
